### ISSUE TITLE
Missing required configuration "schema.registry.url"

### ISSUE THREAD

**Issue by Patafix** [jcustenborder/kafka-connect-influxdb#6]
Hello,
I dont manage to get this connector working, the exception is : 

ERROR Failed to start task influx-0 (org.apache.kafka.connect.runtime.Worker)
io.confluent.common.config.ConfigException: Missing required configuration "schema.registry.url" which has no default value.
	at io.confluent.common.config.ConfigDef.parse(ConfigDef.java:243)
	at io.confluent.common.config.AbstractConfig.&lt;init&gt;(AbstractConfig.java:78)
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerDeConfig.&lt;init&gt;(AbstractKafkaAvroSerDeConfig.java:61)
	at io.confluent.connect.avro.AvroConverterConfig.&lt;init&gt;(AvroConverterConfig.java:27)
	at io.confluent.connect.avro.AvroConverter.configure(AvroConverter.java:59)
	at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:383)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:852)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1600(DistributedHerder.java:108)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$13.call(DistributedHerder.java:866)
	

Where do i need to put this configuration.
I try in in /etc/kafka-connect-influxdb/connect-avro-docker.properties, but no succes.

**Comment by Patafix** [comment]
Fixed with => "value.converter.schema.registry.url": "http://schema-registry:8081",
